### ISSUE TITLE
fetching the public IP

### ISSUE THREAD

**Issue by ulrichard** [JeremyRand/DyName#1]
The  GetIP_SAMPLE_DigIP4 script just grabs the dns record. Doesn't that defeat the purpose of the whole thing? If you have a dynamic IP address, you would still need to run dyndns or similar to populate that DNS record.
Wouldn't it be better to provide a script that finds out the public ip from something like http://whatismyipaddress.com ?

**Comment by JeremyRand** [comment]
The GetIP_SAMPLE_DigIP4 script is for if you have a nameserver that you trust, but which you don't want your users to rely on.  What you suggest is already done by the other sample script: https://github.com/JeremyRand/DyName/blob/master/GetIP_SAMPLE_ICanHazIP

**Comment by ulrichard** [comment]
Oh, how could I overlook that? Thanks for pointing out.
