### ISSUE TITLE
Failed to connect to namecoind

### ISSUE THREAD

**Issue by ulrichard** [JeremyRand/DyName#2]
I always get "Failed to connect to namecoind" from running DyName.py
The same configuration works for p2pool, and I checked it a couple of times.

If I try it in the interactive console, I get this: 

> > > namecoind_session = AuthServiceProxy('http://ulrichard:passwd@127.0.0.1:
> > > 7333')
> > > blockheight = namecoind_session.getblockcount()
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/home/ulrichard/sourcecode/DyName/jsonrpc/authproxy.py", line 98, in **call**
> > >     'Content-type' : 'application/json' })
> > >   File "/usr/lib/python3.4/http/client.py", line 1090, in request
> > >     self._send_request(method, url, body, headers)
> > >   File "/usr/lib/python3.4/http/client.py", line 1128, in _send_request
> > >     self.endheaders(body)
> > >   File "/usr/lib/python3.4/http/client.py", line 1086, in endheaders
> > >     self._send_output(message_body)
> > >   File "/usr/lib/python3.4/http/client.py", line 924, in _send_output
> > >     self.send(msg)
> > >   File "/usr/lib/python3.4/http/client.py", line 859, in send
> > >     self.connect()
> > >   File "/usr/lib/python3.4/http/client.py", line 836, in connect
> > >     self.timeout, self.source_address)
> > >   File "/usr/lib/python3.4/socket.py", line 499, in create_connection
> > >     sock.bind(source_address)
> > > TypeError: getsockaddrarg: AF_INET address must be tuple, not int

Here is the content of ~/.namecoin/bitcoin.conf : 
server=1
daemon=1
rpcpassword=passwd
rpcport=7333
rpcuser=ulrichard
rpcallowip=192.168.2.*

**Comment by ulrichard** [comment]
I played with it for a while. 
With python2 it works. 
With python3 I couldn't get it to run. 
So I just use it with python2 for now.

**Comment by JeremyRand** [comment]
Hmm, that's interesting.  I'll see if I can test sometime soon and see why Py3 would fail on this.  Thanks for the report.
